### ISSUE TITLE
create qr-code-component from the easy file 

### ISSUE THREAD

**Issue by ankitmrmishra** [HACKTOBERFEST-2023-CGC-CEC/web-dev-hactoberfest-2023#5]
In the qr-code-component file I have provided the design image for both mobile and computer version
- make sure to create pixel perfect website 
- You can use any tech Stack
- THE README FILE MUST BE UPDATED 
- Add the project in the folder of the website

## Feel Free to raise Questions here and ask your Doubts

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign me this.
